# Generated by Django 3.1.4 on 2020-12-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganisationAppeal',
        ),
    ]
